#!/bin/bash

echo "=========================================="
echo "Google Search Console Setup Instructions"
echo "=========================================="
echo ""
echo "✓ DNS verification is already complete!"
echo "  TXT record: google-site-verification=fL8XizXZxJifMkLVjEQxnSVLgQCcBSy4JUKBKnAg38g"
echo ""
echo "Next steps for Tyler:"
echo ""
echo "1. Go to: https://search.google.com/search-console"
echo ""
echo "2. Click 'Add Property' and enter: overassessed.ai"
echo ""
echo "3. Select 'Domain property' verification method"
echo ""
echo "4. Choose 'TXT record' verification"
echo ""
echo "5. Click 'VERIFY' (the DNS record is already in place)"
echo ""
echo "6. Once verified, submit the sitemap:"
echo "   Sitemap URL: https://overassessed.ai/sitemap.xml"
echo ""
echo "7. Navigate to Sitemaps section and click 'Add a new sitemap'"
echo "   Enter: sitemap.xml"
echo "   Click 'Submit'"
echo ""
echo "✓ Done! GSC will start indexing your pages."
echo "=========================================="
